# Generated by Django 6.0 on 2025-12-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
