# Generated by Django 6.0 on 2025-12-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_management', '0003_alter_productimages_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='path',
            field=models.CharField(unique=True),
        ),
    ]
