# Generated by Django 6.0 on 2026-01-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_management', '0004_alter_productimages_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='path',
            field=models.CharField(),
        ),
    ]
