# Generated by Django 6.0 on 2026-01-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_management', '0005_alter_productimages_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
