# Generated by Django 6.0 on 2026-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_management', '0009_alter_categories_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
