# Generated by Django 6.0 on 2025-12-11 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_management', '0001_initial'),
        ('users_management', '0003_alter_useraccounts_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeaders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.users')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_management.products')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_management.orderheaders')),
            ],
        ),
    ]
