# Generated by Django 6.0 on 2025-12-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheaders',
            name='method',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderheaders',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
