# Generated by Django 6.0 on 2025-12-25 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0002_orderheaders_method_orderheaders_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders_management.orderheaders'),
        ),
    ]
