# Generated by Django 6.0 on 2026-01-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0003_alter_orderdetails_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderheaders',
            old_name='pay',
            new_name='pay_status',
        ),
    ]
