# Generated by Django 6.0 on 2026-02-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0004_rename_pay_orderheaders_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheaders',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
