# Generated by Django 6.0 on 2026-02-19 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0005_orderheaders_status'),
        ('users_management', '0011_address_number_alter_address_name_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheaders',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderheaders',
            name='number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='orderheaders',
            name='receiver_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderheaders',
            name='receiver_phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderheaders',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderheaders',
            name='ward',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderheaders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_management.users'),
        ),
    ]
