# Generated by Django 6.0 on 2026-02-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0006_orderheaders_city_orderheaders_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='current_price',
            field=models.FloatField(default=0),
        ),
    ]
