# Generated by Django 6.0 on 2026-02-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0007_orderdetails_current_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderheaders',
            old_name='status',
            new_name='order_status',
        ),
    ]
