# Generated by Django 6.0 on 2026-02-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0008_rename_status_orderheaders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheaders',
            name='expire_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
