# Generated by Django 6.0 on 2026-02-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0010_alter_orderheaders_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheaders',
            name='expire_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderheaders',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
