# Generated by Django 6.0 on 2026-02-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0011_alter_orderheaders_expire_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheaders',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
