# Generated by Django 6.0 on 2026-02-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0012_orderheaders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderheaders',
            name='status',
        ),
    ]
