# Generated by Django 6.0 on 2026-02-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0013_remove_orderheaders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheaders',
            name='pay_status',
            field=models.IntegerField(default=0),
        ),
    ]
