# Generated by Django 6.0 on 2026-02-06 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_child', to='carts_management.cartheaders'),
        ),
    ]
