# Generated by Django 6.0 on 2026-02-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_management', '0002_alter_cartdetails_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartheaders',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
