# Generated by Django 6.0 on 2026-02-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_management', '0005_alter_cartdetails_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
