# Generated by Django 6.0 on 2026-02-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_management', '0006_alter_cartdetails_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartheaders',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
