# Generated by Django 6.0 on 2026-02-26 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_management', '0007_alter_cartheaders_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
