# Generated by Django 6.0 on 2025-12-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccounts',
            old_name='account_id',
            new_name='id',
        ),
    ]
