# Generated by Django 6.0 on 2025-12-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0002_rename_account_id_useraccounts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
