# Generated by Django 6.0 on 2025-12-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0003_alter_useraccounts_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
