# Generated by Django 6.0 on 2025-12-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0004_users_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='avt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
