# Generated by Django 6.0 on 2025-12-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0005_useraccounts_avt'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
    ]
