# Generated by Django 6.0 on 2025-12-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0006_users_is_male'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='avt',
            field=models.CharField(default='/user.png', max_length=100),
        ),
    ]
