# Generated by Django 6.0 on 2025-12-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0007_alter_useraccounts_avt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='avt',
            field=models.CharField(default='/user.png', max_length=200),
        ),
    ]
