# Generated by Django 6.0 on 2026-01-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0008_alter_useraccounts_avt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='avt',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
