# Generated by Django 6.0 on 2026-02-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0010_remove_users_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='name_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_2',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
