# Generated by Django 6.0 on 2026-02-19 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0011_address_number_alter_address_name_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name_2',
            new_name='receiver_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='phone_2',
            new_name='receiver_phone',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='users_management.users'),
        ),
    ]
