# Generated by Django 6.0 on 2025-12-10 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrderDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cus_description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_management.materials')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUploaded',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.FilePathField()),
                ('type', models.CharField(max_length=10)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_management.serviceorderdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrderHeaders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='serviceorderdetails',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_management.serviceorderheaders'),
        ),
        migrations.AddField(
            model_name='serviceorderdetails',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_management.services'),
        ),
    ]
