# Generated by Django 6.0 on 2026-01-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderheaders',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
