# Generated by Django 6.0 on 2026-03-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_management', '0002_serviceorderheaders_pay_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorderdetails',
            name='header',
        ),
        migrations.RemoveField(
            model_name='serviceorderdetails',
            name='material',
        ),
        migrations.RemoveField(
            model_name='serviceorderdetails',
            name='service',
        ),
        migrations.RemoveField(
            model_name='customeruploaded',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='serviceorderheaders',
            name='user',
        ),
        migrations.AddField(
            model_name='customeruploaded',
            name='public_file_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customeruploaded',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customeruploaded',
            name='type',
            field=models.CharField(default='image', max_length=100),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='ServiceOrderDetails',
        ),
        migrations.DeleteModel(
            name='ServiceOrderHeaders',
        ),
    ]
