# Generated by Django 6.0 on 2026-03-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_management', '0003_remove_serviceorderdetails_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruploaded',
            name='type',
            field=models.CharField(default='avt', max_length=100),
        ),
    ]
