# Generated by Django 6.0 on 2026-03-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_management', '0004_alter_customeruploaded_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruploaded',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
